version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - static:/static
    depends_on:
      - web
  web:
    build: .
    volumes:
      - .:/code
      - static:/static
    env_file:
      - db.env
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - db.env

volumes:
  static:
