version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static:/mnt/static
    depends_on:
      - web

  web:
    build: .
    volumes:
      - .:/code
      - media:/mnt/media
      - static:/mnt/static
    env_file:
      - db.env
    depends_on:
      - db

  db:
    image: postgres:10
    env_file:
      - db.env

volumes:
  media:
  static:
