# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-11 13:45
from __future__ import unicode_literals

import ddweb.apps.images.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("contenttypes", "0002_remove_content_type_name")]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(upload_to=ddweb.apps.images.models.file_name),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        )
    ]
